name: pandas-flavor
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas>=0.23
  - xarray
  - pip
  - pre-commit
  - pytest # for tests
  - black # code formatting
  - twine # for uploading to PyPI
  - bump2version
  - setuptools==70.3.0
  - build # for building package distributions
  - pip:
      - tuna
